name: HSH-Data-Exchange
main: de.headshotharp.web.plugin.DataExchangePlugin
version: 1.19.3
api-version: 1.19
api: []
author: HeadShotHarp
description: Data-Exchange Plugin for PaperMC 1.19.2
commands:
  hsh:
    description: Desc
    usage: |
           /<command> create <central/user> <material>
           /<command> delete <central/user> [confirm]
  pm:
    description: Permissions Manager
    usage: |
           /<command> role create <name>
           /<command> role promote <name>
  blocks:
    description: Shows block statistics
    usage: /blocks
