server:
  port: 8080
  shutdown: graceful
  tomcat:
    remoteip:
      protocol-header: X-Forwarded-Proto
  error:
    path: /error

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
    open-in-view: false
    hibernate:
      ddl-auto: update
  mvc:
    servlet:
      load-on-startup: 1
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
